# Generated by Django 5.0.6 on 2024-07-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recurso_alter_servico_icone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('preco', models.CharField(max_length=100, verbose_name='Preço')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('botao', models.CharField(max_length=100, verbose_name='Botão')),
            ],
            options={
                'verbose_name': 'Preço',
                'verbose_name_plural': 'Preços',
            },
        ),
        migrations.AlterField(
            model_name='recurso',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-laptop-phone', 'Computador'), ('lni-layers', 'Camadas'), ('lni-cog', 'Engrenagem'), ('lni-leaf', 'Folha')], max_length=16, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuário'), ('lni-cog', 'Engrenagem'), ('lni-mobile', 'Mobile'), ('lni-layers', 'Design')], max_length=12, verbose_name='Icone'),
        ),
    ]
