# Generated by Django 5.0.6 on 2024-07-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_preco_descricao_preco_descricao_gb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preco',
            name='icone',
            field=models.CharField(choices=[('lni-package', 'Caixa'), ('lni-star', 'Estrela'), ('lni-drop', 'Agua')], default='a', max_length=16, verbose_name='Icone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preco',
            name='descricao_gb',
            field=models.CharField(max_length=100, verbose_name='Descrição gb'),
        ),
        migrations.AlterField(
            model_name='preco',
            name='descricao_suporte',
            field=models.CharField(max_length=100, verbose_name='Descrição sup'),
        ),
        migrations.AlterField(
            model_name='preco',
            name='descricao_updates',
            field=models.CharField(max_length=100, verbose_name='Descrição up'),
        ),
        migrations.AlterField(
            model_name='preco',
            name='descricao_users',
            field=models.CharField(max_length=100, verbose_name='Descrição users'),
        ),
        migrations.AlterField(
            model_name='preco',
            name='tipo_plano',
            field=models.CharField(max_length=100, verbose_name='Plano'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='icone',
            field=models.CharField(choices=[('lni-leaf', 'Folha'), ('lni-cog', 'Engrenagem'), ('lni-rocket', 'Foguete'), ('lni-layers', 'Camadas'), ('lni-laptop-phone', 'Computador')], max_length=16, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='icone',
            field=models.CharField(choices=[('lni-mobile', 'Mobile'), ('lni-users', 'Usuário'), ('lni-stats-up', 'Gráfico'), ('lni-layers', 'Design'), ('lni-rocket', 'Foguete'), ('lni-cog', 'Engrenagem')], max_length=12, verbose_name='Icone'),
        ),
    ]
